apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test
  name: config-map-test
data:
  WORDPRESS_DB_HOST: mysql-test-svc
  MYSQL_DATABASE: wordpressdb
  MYSQL_USER: mysqlwpadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: production
  name: config-map-production
data:
  WORDPRESS_DB_HOST: mysql-prod-svc
  MYSQL_DATABASE: wordpressdb
  MYSQL_USER: mysqlwpadmin